version: 0.2

# 참고 https://jojoldu.tistory.com/282#recentEntries
#env:
#  variables:
#    DIV:

phases:
  install:
    commands:
      - export DIV="\n==================================================\n"
      - printf $DIV"INSTALL PHASE START AT $(date +"%Y-%m-%d %H:%M:%S")"$DIV
      - printf $DIV"INSTALL AWS CLI V2 START AT $(date +"%Y-%m-%d %H:%M:%S")"$DIV
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - printf $DIV"AWS VERSION IS $(/usr/local/bin/aws --version)"$DIV
      - printf $DIV"JAVA VERSION IS $(java -version)"$DIV
  #      - echo $DIV
  #      - echo "setting aws config file at $(date +"%Y-%m-%d %H:%M:%S")"
  #      - export AWS_CONFIG_PATH=~/.aws
  #      - export AWS_CONFIG_CREDENTIALS=credentials
  #      - export AWS_CONFIG_CONFIG=config
  #      - mkdir $AWS_CONFIG_PATH
  #      - echo "[default]" >> $AWS_CONFIG_PATH/$AWS_CONFIG_CREDENTIALS
  #      - echo "aws_access_key_id = $AWS_KEY_ID" >> $AWS_CONFIG_PATH/$AWS_CONFIG_CREDENTIALS
  #      - echo "aws_secret_access_key = $AWS_KEY_VALUE" >> $AWS_CONFIG_PATH/$AWS_CONFIG_CREDENTIALS
  #      - echo "[default]" >> $AWS_CONFIG_PATH/$AWS_CONFIG_CONFIG
  #      - echo "region = ap-northeast-2" >> $AWS_CONFIG_PATH/$AWS_CONFIG_CONFIG
  #      - cat $AWS_CONFIG_PATH/$AWS_CONFIG_CREDENTIALS
  #      - cat $AWS_CONFIG_PATH/$AWS_CONFIG_CONFIG
  build:
    commands:
      - export DOCKER_IMAGE_NAME=msa.member
      - export DOCKER_IMAGE_TAG=$(date +"%Y%m%d%H%M%S")
      - printf $DIV"BUILD PHASE START -> $(date +"%Y-%m-%d %H:%M:%S")"$DIV
      - printf $DIV"BOOT JAR BUILD START -> $(date +"%Y-%m-%d %H:%M:%S")"$DIV
      - chmod +x ./gradlew
      - ./gradlew bootJar
      - printf $DIV"BOOT JAR -> $(ls ./build/libs)"$DIV
      - printf $DIV"DOCKER VERSION -> $(docker --version)"$DIV
      - printf $DIV"DOCKER IMAGE TAG -> $DOCKER_IMAGE_TAG"$DIV
      - printf $DIV"DOCKER IMAGE BUILD START -> $(date +"%Y-%m-%d %H:%M:%S")"$DIV
      - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
  post_build:
    commands:
      - export MSA_DOCKER_REPOSITORY=081582853021.dkr.ecr.ap-northeast-2.amazonaws.com
      - printf $DIV"POST BUILD PHASE START -> $(date +"%Y-%m-%d %H:%M:%S")"$DIV
      - /usr/local/bin/aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin $MSA_DOCKER_REPOSITORY/$DOCKER_IMAGE_NAME
      - printf $DIV"DOCKER IMAGES -> $(docker images)"$DIV
      #      aws s3 bucket 으로 파일을 올린다.
      #      - aws s3 sync ./build/libs/ s3://msa-codebuild/build/libs
      #      docker registry 에 latest, $DOCKER_IMAGE_TAG 의 태그로 push 한다
      - docker tag $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG $MSA_DOCKER_REPOSITORY/$DOCKER_IMAGE_NAME:latest
      - docker tag $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG $MSA_DOCKER_REPOSITORY/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
      - docker push $MSA_DOCKER_REPOSITORY/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
      - docker push $MSA_DOCKER_REPOSITORY/$DOCKER_IMAGE_NAME:latest
      #      slack push
      - export SLACK_TEXT="build done, docker image"
      - sh ./alarm-slack.sh
cache:
  paths:
    - '.gradle/caches/**/*'