spring:
  datasource:
    hikari:
      maximum-pool-size: 4

mybatis:
  type-aliases-package: com.jsm.dto.model
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: com/jsm/mapper/**/*.xml


logging:
  level:
    root: DEBUG
    com:
      jsm : DEBUG