server:
  port: 8090

spring:
  datasource:
    hikari:
      maximum-pool-size: 4

mybatis:
  type-aliases-package: com.jsm.dto.model
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: com/jsm/mapper/**/*.xml

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

logging:
  level:
    root: INFO
    com:
      jsm : DEBUG